set -ex
# python main.py darkflpa boosted --suffix exps/1105_darkflpa/$1 --kd_direction $1 --kd_knowledge response --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature False  --loss_type ce-kd_loss --sw learn --sw_type soft


# python main.py darkflpa boosted --diff_generator --suffix exps/1106_darkflpa_diff_sl_newsw/$1_soft --kd_direction sl --kd_knowledge relation --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --loss_type $1 --sw learn --sw_type soft
# python main.py darkflpa boosted --diff_generator --suffix exps/1106_darkflpa_diff_sl_newsw/$1_hard --kd_direction sl --kd_knowledge relation --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --loss_type $1 --sw learn --sw_type hard
# python main.py darkflpa boosted --diff_generator --suffix exps/1106_darkflpa_diff_sl_newsw/$1_soft --kd_direction sl --kd_knowledge relation --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --loss_type $1 --sw none  --sw_type soft
# python main.py darkflpa boosted --diff_generator --suffix exps/1106_darkflpa_diff_sl_newsw/$1_hard --kd_direction sl --kd_knowledge relation --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --loss_type $1 --sw none  --sw_type hard


# python main.py darkflpa boosted --diff_generator --s_gamma $1 --suffix exps/1110_darkflpa_p/s_gamma${1}/p30   --kd_direction sl --kd_knowledge relation --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --loss_type kd_loss --sw learn --sw_type soft --exit_p 30
# python main.py darkflpa boosted --diff_generator --s_gamma $1 --suffix exps/1110_darkflpa_p/s_gamma${1}/p39   --kd_direction sl --kd_knowledge relation --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --loss_type kd_loss --sw learn --sw_type soft --exit_p 39
# python main.py darkflpa boosted --diff_generator --s_gamma $1 --suffix exps/1110_darkflpa_p/s_gamma${1}/p20   --kd_direction sl --kd_knowledge relation --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --loss_type kd_loss --sw learn --sw_type soft --exit_p 20
# python main.py darkflpa boosted --diff_generator --s_gamma $1 --suffix exps/1110_darkflpa_p/s_gamma${1}/p10   --kd_direction sl --kd_knowledge relation --kd_join last --device $2 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --loss_type kd_loss --sw learn --sw_type soft --exit_p 10


python main.py darkflpa boosted --diff_generator --g_gap 0 --s_gamma 1 --suffix exps/1111_darkflpa_s_gamma1/${2}_last_kd --loss_type kd_loss --kd_direction $2 --kd_knowledge relation --kd_join last --device $1 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --sw learn --sw_type soft --exit_p 30

python main.py darkflpa boosted --diff_generator --g_gap 0 --s_gamma 1 --suffix exps/1111_darkflpa_s_gamma1/${2}_last_ce-kd --loss_type ce-kd_loss --kd_direction $2 --kd_knowledge relation --kd_join last --device $1 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --sw learn --sw_type soft --exit_p 30

python main.py darkflpa boosted --diff_generator --g_gap 0 --s_gamma 1 --suffix exps/1111_darkflpa_s_gamma1/${2}_last_ce --loss_type ce_loss --kd_direction $2 --kd_knowledge relation --kd_join last --device $1 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --sw learn --sw_type soft --exit_p 30

python main.py darkflpa boosted --diff_generator --g_gap 0 --s_gamma 1 --suffix exps/1111_darkflpa_s_gamma1/${2}_all_kd --loss_type kd_loss --kd_direction $2 --kd_knowledge relation --kd_join all --device $1 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --sw learn --sw_type soft --exit_p 30

python main.py darkflpa boosted --diff_generator --g_gap 0 --s_gamma 1 --suffix exps/1111_darkflpa_s_gamma1/${2}_all_ce-kd --loss_type ce-kd_loss --kd_direction $2 --kd_knowledge relation --kd_join all --device $1 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --sw learn --sw_type soft --exit_p 30

python main.py darkflpa boosted --diff_generator --g_gap 0 --s_gamma 1 --suffix exps/1111_darkflpa_s_gamma1/${2}_all_ce --loss_type ce_loss --kd_direction $2 --kd_knowledge relation --kd_join all --device $1 --dataset cifar100-224-d03 --model vit --sr 0.1 --total_num 120 --lr 0.05 --s_epoches 2 --valid_gap 10 --rnd 500 --is_feature True --sw learn --sw_type soft --exit_p 30
